// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slbsfekmcljmudybazna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsYnNmZWttY2xqbXVkeWJhem5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzIwNTcsImV4cCI6MjA2MDQwODA1N30.hTHfyt2gWexyo_kUEeC9WmOoTkFm0VLPI6P9rqZu4-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);